version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: awalach/openvpn
    container_name: openvpn-if
    ports:
     - "1198:1194/udp"
    restart: always
    depends_on:
      - "gui"
    volumes:
     - ovpn-as-data:/etc/openvpn
  gui:
    image: awalach/openvpn-web-ui
    container_name: openvpn-gui
    ports:
     - "8090:8080/tcp"
    restart: always
    volumes:
     - ovpn-as-data:/etc/openvpn
     - ovpn-as-db:/opt/openvpn-gui/db
